import type { Metadata } from 'next';
import LuksoWebComponentsProvider from './LuksoWebComponentsProvider';
import './globals.scss';

export const metadata: Metadata = {
  title: 'LUKSO MiniApp Nextjs Template',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LuksoWebComponentsProvider>{children}</LuksoWebComponentsProvider>
      </body>
    </html>
  );
}
